DEL /F /Q Windows\inf\compositebus.PNF
DEL /F /Q Windows\inf\lltdio.PNF
DEL /F /Q Windows\inf\rspndr.PNF
DEL /F /Q Windows\inf\wfplwf.PNF
DEL /F /Q Windows\inf\adp94xx.PNF
DEL /F /Q Windows\inf\averhbh826_noaverir_x64.PNF
DEL /F /Q Windows\inf\bthspp.PNF
DEL /F /Q Windows\inf\cxraptor_fm1216mk5_ibv64.PNF
DEL /F /Q Windows\inf\cxraptor_fm1236mk5_ibv64.PNF
DEL /F /Q Windows\inf\mdmmts.PNF
DEL /F /Q Windows\inf\mdmtkr.PNF
DEL /F /Q Windows\inf\rdpbus.PNF
DEL /F /Q Windows\inf\angel264.PNF
DEL /F /Q Windows\inf\faxca003.PNF
DEL /F /Q Windows\inf\faxcn001.PNF
DEL /F /Q Windows\inf\faxcn002.PNF
DEL /F /Q Windows\inf\mdmbr002.PNF
DEL /F /Q Windows\inf\mdmgl001.PNF
DEL /F /Q Windows\inf\mdmgl002.PNF
DEL /F /Q Windows\inf\mdmgl003.PNF
DEL /F /Q Windows\inf\mdmgl004.PNF
DEL /F /Q Windows\inf\mdmgl010.PNF
DEL /F /Q Windows\inf\mdmzyp.PNF
DEL /F /Q Windows\inf\memory.PNF
DEL /F /Q Windows\inf\netr28x.PNF
DEL /F /Q Windows\inf\nettun.PNF
DEL /F /Q Windows\inf\umpass.PNF
DEL /F /Q Windows\inf\wiacn001.PNF
DEL /F /Q Windows\inf\winusb.PNF
DEL /F /Q Windows\inf\wpdmtp.PNF
DEL /F /Q Windows\inf\hpoa1nd.PNF
DEL /F /Q Windows\inf\mdmbr004.PNF
DEL /F /Q Windows\inf\mdmbr005.PNF
DEL /F /Q Windows\inf\mdmbr006.PNF
DEL /F /Q Windows\inf\mdmbr007.PNF
DEL /F /Q Windows\inf\mdmbr008.PNF
DEL /F /Q Windows\inf\mdmdcm5.PNF
DEL /F /Q Windows\inf\mdmdcm6.PNF
DEL /F /Q Windows\inf\mdmgl005.PNF
DEL /F /Q Windows\inf\mdmgl006.PNF
DEL /F /Q Windows\inf\mdmgl007.PNF
DEL /F /Q Windows\inf\mdmgl008.PNF
DEL /F /Q Windows\inf\mdmgl009.PNF
DEL /F /Q Windows\inf\netl160a.PNF
DEL /F /Q Windows\inf\prnca003.PNF
DEL /F /Q Windows\inf\wiabr002.PNF
DEL /F /Q Windows\inf\wiabr004.PNF
DEL /F /Q Windows\inf\wiabr005.PNF
DEL /F /Q Windows\inf\wiabr006.PNF
DEL /F /Q Windows\inf\wiaep002.PNF
DEL /F /Q Windows\inf\wiaep003.PNF
DEL /F /Q Windows\inf\wiahp001.PNF
DEL /F /Q Windows\inf\wiasa002.PNF
DEL /F /Q Windows\inf\hpoa1sd.PNF
DEL /F /Q Windows\inf\mdm3com.PNF
DEL /F /Q Windows\inf\mdmbug3.PNF
DEL /F /Q Windows\inf\mdmbw561.PNF
DEL /F /Q Windows\inf\mdmcom1.PNF
DEL /F /Q Windows\inf\mdmcpq2.PNF
DEL /F /Q Windows\inf\mdmhay2.PNF
DEL /F /Q Windows\inf\mdmmc288.PNF
DEL /F /Q Windows\inf\netbc664.PNF
DEL /F /Q Windows\inf\netl1c64.PNF
DEL /F /Q Windows\inf\netl1e64.PNF
DEL /F /Q Windows\inf\netl260a.PNF
DEL /F /Q Windows\inf\prnbr002.PNF
DEL /F /Q Windows\inf\prnbr003.PNF
DEL /F /Q Windows\inf\prnep002.PNF
DEL /F /Q Windows\inf\prnge001.PNF
DEL /F /Q Windows\inf\prnle002.PNF
DEL /F /Q Windows\inf\prnle003.PNF
DEL /F /Q Windows\inf\prnle004.PNF
DEL /F /Q Windows\inf\prnod002.PNF
DEL /F /Q Windows\inf\prnrc002.PNF
DEL /F /Q Windows\inf\prnsa002.PNF
DEL /F /Q Windows\inf\wiabr007.PNF
DEL /F /Q Windows\inf\wiabr008.PNF
DEL /F /Q Windows\inf\wiabr009.PNF
DEL /F /Q Windows\inf\dc21x4vm.PNF
DEL /F /Q Windows\inf\hpoa1so.PNF
DEL /F /Q Windows\inf\netvwifibus.PNF
DEL /F /Q Windows\inf\prnbr004.PNF
DEL /F /Q Windows\inf\prnbr005.PNF
DEL /F /Q Windows\inf\prnbr006.PNF
DEL /F /Q Windows\inf\prnbr007.PNF
DEL /F /Q Windows\inf\prnep003.PNF
DEL /F /Q Windows\inf\prnep004.PNF
DEL /F /Q Windows\inf\prnep005.PNF
DEL /F /Q Windows\inf\prnhp002.PNF
DEL /F /Q Windows\inf\prnhp003.PNF
DEL /F /Q Windows\inf\prnin002.PNF
DEL /F /Q Windows\inf\prnin003.PNF
DEL /F /Q Windows\inf\prnin004.PNF
DEL /F /Q Windows\inf\prnkm002.PNF
DEL /F /Q Windows\inf\prnkm003.PNF
DEL /F /Q Windows\inf\prnrc003.PNF
DEL /F /Q Windows\inf\prnrc004.PNF
DEL /F /Q Windows\inf\prnrc005.PNF
DEL /F /Q Windows\inf\prnrc006.PNF
DEL /F /Q Windows\inf\wiaky002.PNF
DEL /F /Q Windows\inf\wialx002.PNF
DEL /F /Q Windows\inf\wialx003.PNF
DEL /F /Q Windows\inf\wialx004.PNF
DEL /F /Q Windows\inf\wialx005.PNF
DEL /F /Q Windows\inf\wialx006.PNF
DEL /F /Q Windows\inf\af9035bda.PNF
DEL /F /Q Windows\inf\hpoa1ss.PNF
DEL /F /Q Windows\inf\mdmntt1.PNF
DEL /F /Q Windows\inf\mdmsun1.PNF
DEL /F /Q Windows\inf\prnbr008.PNF
DEL /F /Q Windows\inf\prnbr009.PNF
DEL /F /Q Windows\inf\prnfx002.PNF
DEL /F /Q Windows\inf\prngt002.PNF
DEL /F /Q Windows\inf\prngt003.PNF
DEL /F /Q Windows\inf\prngt004.PNF
DEL /F /Q Windows\inf\prnhp004.PNF
DEL /F /Q Windows\inf\prnhp005.PNF
DEL /F /Q Windows\inf\prnkm004.PNF
DEL /F /Q Windows\inf\prnkm005.PNF
DEL /F /Q Windows\inf\prnms002.PNF
DEL /F /Q Windows\inf\prnnr002.PNF
DEL /F /Q Windows\inf\prnnr003.PNF
DEL /F /Q Windows\inf\prnnr004.PNF
DEL /F /Q Windows\inf\prnok002.PNF
DEL /F /Q Windows\inf\prnrc007.PNF
DEL /F /Q Windows\inf\prnsh002.PNF
DEL /F /Q Windows\inf\prnso002.PNF
DEL /F /Q Windows\inf\wiaxx002.PNF
DEL /F /Q Windows\inf\adpahci.PNF
DEL /F /Q Windows\inf\averfx2swtv_noavin_x64.PNF
DEL /F /Q Windows\inf\mdmsun2.PNF
DEL /F /Q Windows\inf\net1kx64.PNF
DEL /F /Q Windows\inf\net1qx64.PNF
DEL /F /Q Windows\inf\prnky002.PNF
DEL /F /Q Windows\inf\prnky003.PNF
DEL /F /Q Windows\inf\prnky004.PNF
DEL /F /Q Windows\inf\prnky005.PNF
DEL /F /Q Windows\inf\prnky006.PNF
DEL /F /Q Windows\inf\prnky007.PNF
DEL /F /Q Windows\inf\prnky008.PNF
DEL /F /Q Windows\inf\prnlx002.PNF
DEL /F /Q Windows\inf\prnlx003.PNF
DEL /F /Q Windows\inf\prnlx004.PNF
DEL /F /Q Windows\inf\prnlx005.PNF
DEL /F /Q Windows\inf\prnlx006.PNF
DEL /F /Q Windows\inf\prnlx007.PNF
DEL /F /Q Windows\inf\prnsv002.PNF
DEL /F /Q Windows\inf\prnts002.PNF
DEL /F /Q Windows\inf\prnts003.PNF
DEL /F /Q Windows\inf\wiaca00a.PNF
DEL /F /Q Windows\inf\wiaca00b.PNF
DEL /F /Q Windows\inf\wiaca00c.PNF
DEL /F /Q Windows\inf\wiaca00d.PNF
DEL /F /Q Windows\inf\wiaca00e.PNF
DEL /F /Q Windows\inf\wiaca00f.PNF
DEL /F /Q Windows\inf\1394.PNF
DEL /F /Q Windows\inf\dot4prt.PNF
DEL /F /Q Windows\inf\hiddigi.PNF
DEL /F /Q Windows\inf\mdmboca.PNF
DEL /F /Q Windows\inf\mdmbr00a.PNF
DEL /F /Q Windows\inf\mf.PNF
DEL /F /Q Windows\inf\net1yx64.PNF
DEL /F /Q Windows\inf\netw5v64.PNF
DEL /F /Q Windows\inf\prnca00a.PNF
DEL /F /Q Windows\inf\prnca00b.PNF
DEL /F /Q Windows\inf\prnky009.PNF
DEL /F /Q Windows\inf\prnlx008.PNF
DEL /F /Q Windows\inf\prnlx009.PNF
DEL /F /Q Windows\inf\prnsv003.PNF
DEL /F /Q Windows\inf\prnsv004.PNF
DEL /F /Q Windows\inf\prnxx002.PNF
DEL /F /Q Windows\inf\wiabr00a.PNF
DEL /F /Q Windows\inf\wiaca00i.PNF
DEL /F /Q Windows\inf\amdsata.PNF
DEL /F /Q Windows\inf\brmfcmf.PNF
DEL /F /Q Windows\inf\hdaudio.PNF
DEL /F /Q Windows\inf\ks.PNF
DEL /F /Q Windows\inf\mdmagm64.PNF
DEL /F /Q Windows\inf\mdmaiwa.PNF
DEL /F /Q Windows\inf\mdmarch.PNF
DEL /F /Q Windows\inf\mdmdf56f.PNF
DEL /F /Q Windows\inf\mdmeric.PNF
DEL /F /Q Windows\inf\mdmhaeu.PNF
DEL /F /Q Windows\inf\mdmjf56e.PNF
DEL /F /Q Windows\inf\mdmmega.PNF
DEL /F /Q Windows\inf\mdmpace.PNF
DEL /F /Q Windows\inf\nete1e3e.PNF
DEL /F /Q Windows\inf\nete1g3e.PNF
DEL /F /Q Windows\inf\prnca00c.PNF
DEL /F /Q Windows\inf\prnca00d.PNF
DEL /F /Q Windows\inf\prnca00e.PNF
DEL /F /Q Windows\inf\prnca00f.PNF
DEL /F /Q Windows\inf\prnca00g.PNF
DEL /F /Q Windows\inf\prnca00h.PNF
DEL /F /Q Windows\inf\prnca00i.PNF
DEL /F /Q Windows\inf\wd.PNF
DEL /F /Q Windows\inf\acpipmi.PNF
DEL /F /Q Windows\inf\angelu64.PNF
DEL /F /Q Windows\inf\crcdisk.PNF
DEL /F /Q Windows\inf\mdmags64.PNF
DEL /F /Q Windows\inf\mdmelsa.PNF
DEL /F /Q Windows\inf\mdmolic.PNF
DEL /F /Q Windows\inf\megasas.PNF
DEL /F /Q Windows\inf\net44amd.PNF
DEL /F /Q Windows\inf\netirda.PNF
DEL /F /Q Windows\inf\ph3xibc0.PNF
DEL /F /Q Windows\inf\ph3xibc1.PNF
DEL /F /Q Windows\inf\ph3xibc2.PNF
DEL /F /Q Windows\inf\ph3xibc3.PNF
DEL /F /Q Windows\inf\ph3xibc4.PNF
DEL /F /Q Windows\inf\ph3xibc5.PNF
DEL /F /Q Windows\inf\ph3xibc6.PNF
DEL /F /Q Windows\inf\ph3xibc7.PNF
DEL /F /Q Windows\inf\prnbr00a.PNF
DEL /F /Q Windows\inf\prnep00a.PNF
DEL /F /Q Windows\inf\prnep00b.PNF
DEL /F /Q Windows\inf\prnep00c.PNF
DEL /F /Q Windows\inf\prnrc00a.PNF
DEL /F /Q Windows\inf\prnrc00b.PNF
DEL /F /Q Windows\inf\divacx64.PNF
DEL /F /Q Windows\inf\hdaudss.PNF
DEL /F /Q Windows\inf\lsi_sas.PNF
DEL /F /Q Windows\inf\mdmcomp.PNF
DEL /F /Q Windows\inf\mdmdyna.PNF
DEL /F /Q Windows\inf\mdmisdn.PNF
DEL /F /Q Windows\inf\mdmmcom.PNF
DEL /F /Q Windows\inf\mdmrock.PNF
DEL /F /Q Windows\inf\mdmsier.PNF
DEL /F /Q Windows\inf\mdmsii64.PNF
DEL /F /Q Windows\inf\netb57va.PNF
DEL /F /Q Windows\inf\netvg62a.PNF
DEL /F /Q Windows\inf\ph3xibc8.PNF
DEL /F /Q Windows\inf\ph3xibc9.PNF
DEL /F /Q Windows\inf\prnca00x.PNF
DEL /F /Q Windows\inf\prnca00y.PNF
DEL /F /Q Windows\inf\prnca00z.PNF
DEL /F /Q Windows\inf\prnep00d.PNF
DEL /F /Q Windows\inf\prnep00e.PNF
DEL /F /Q Windows\inf\prnep00f.PNF
DEL /F /Q Windows\inf\prnep00g.PNF
DEL /F /Q Windows\inf\prnrc00c.PNF
DEL /F /Q Windows\inf\ramdisk.PNF
DEL /F /Q Windows\inf\sffdisk.PNF
DEL /F /Q Windows\inf\battery.PNF
DEL /F /Q Windows\inf\display.PNF
DEL /F /Q Windows\inf\eaphost.PNF
DEL /F /Q Windows\inf\hidserv.PNF
DEL /F /Q Windows\inf\mdmmot64.PNF
DEL /F /Q Windows\inf\mdmnova.PNF
DEL /F /Q Windows\inf\mdmpenr.PNF
DEL /F /Q Windows\inf\netmyk00.PNF
DEL /F /Q Windows\inf\netnvma.PNF
DEL /F /Q Windows\inf\prnep00l.PNF
DEL /F /Q Windows\inf\prnlx00a.PNF
DEL /F /Q Windows\inf\prnlx00b.PNF
DEL /F /Q Windows\inf\prnlx00c.PNF
DEL /F /Q Windows\inf\prnlx00d.PNF
DEL /F /Q Windows\inf\prnlx00e.PNF
DEL /F /Q Windows\inf\scsidev.PNF
DEL /F /Q Windows\inf\vsmraid.PNF
DEL /F /Q Windows\inf\wpdcomp.PNF
DEL /F /Q Windows\inf\61883.PNF
DEL /F /Q Windows\inf\iastorv.PNF
DEL /F /Q Windows\inf\mdmnttp.PNF
DEL /F /Q Windows\inf\mdmoptn.PNF
DEL /F /Q Windows\inf\mdmtron.PNF
DEL /F /Q Windows\inf\mdmusrf.PNF
DEL /F /Q Windows\inf\mdmusrg.PNF
DEL /F /Q Windows\inf\mdmvdot.PNF
DEL /F /Q Windows\inf\mdmzoom.PNF
DEL /F /Q Windows\inf\monitor.PNF
DEL /F /Q Windows\inf\msmouse.PNF
DEL /F /Q Windows\inf\netloop.PNF
DEL /F /Q Windows\inf\netnvm64.PNF
DEL /F /Q Windows\inf\netrtl64.PNF
DEL /F /Q Windows\inf\netvfx64.PNF
DEL /F /Q Windows\inf\netxex64.PNF
DEL /F /Q Windows\inf\netxfx64.PNF
DEL /F /Q Windows\inf\rawsilo.PNF
DEL /F /Q Windows\inf\volsnap.PNF
DEL /F /Q Windows\inf\elxstor.PNF
DEL /F /Q Windows\inf\mdmaiwa3.PNF
DEL /F /Q Windows\inf\mdmaiwa4.PNF
DEL /F /Q Windows\inf\mdmaiwa5.PNF
DEL /F /Q Windows\inf\mdmeric2.PNF
DEL /F /Q Windows\inf\megasas2.PNF
DEL /F /Q Windows\inf\netefe3e.PNF
DEL /F /Q Windows\inf\netr28ux.PNF
DEL /F /Q Windows\inf\netrtx64.PNF
DEL /F /Q Windows\inf\ntprint.PNF
DEL /F /Q Windows\inf\ph3xibc10.PNF
DEL /F /Q Windows\inf\ph3xibc11.PNF
DEL /F /Q Windows\inf\ph3xibc12.PNF
DEL /F /Q Windows\inf\prnlx00v.PNF
DEL /F /Q Windows\inf\prnlx00w.PNF
DEL /F /Q Windows\inf\prnlx00x.PNF
DEL /F /Q Windows\inf\prnlx00y.PNF
DEL /F /Q Windows\inf\prnlx00z.PNF
DEL /F /Q Windows\inf\tsprint.PNF
DEL /F /Q Windows\inf\unknown.PNF
DEL /F /Q Windows\inf\usbstor.PNF
DEL /F /Q Windows\inf\atiriol6.PNF
DEL /F /Q Windows\inf\bda.PNF
DEL /F /Q Windows\inf\fdc.PNF
DEL /F /Q Windows\inf\lsi_sas2.PNF
DEL /F /Q Windows\inf\mdmatm2k.PNF
DEL /F /Q Windows\inf\mdmcxhv6.PNF
DEL /F /Q Windows\inf\mdmnttd2.PNF
DEL /F /Q Windows\inf\mdmomrn3.PNF
DEL /F /Q Windows\inf\mdmrock3.PNF
DEL /F /Q Windows\inf\mdmrock4.PNF
DEL /F /Q Windows\inf\mdmrock5.PNF
DEL /F /Q Windows\inf\mdmtdkj2.PNF
DEL /F /Q Windows\inf\mdmtdkj3.PNF
DEL /F /Q Windows\inf\mdmtdkj4.PNF
DEL /F /Q Windows\inf\mdmtdkj5.PNF
DEL /F /Q Windows\inf\mdmtdkj6.PNF
DEL /F /Q Windows\inf\mdmtdkj7.PNF
DEL /F /Q Windows\inf\mdmwhql0.PNF
DEL /F /Q Windows\inf\msports.PNF
DEL /F /Q Windows\inf\sisraid2.PNF
DEL /F /Q Windows\inf\sisraid4.PNF
DEL /F /Q Windows\inf\wudfusbcciddriver.PNF
DEL /F /Q Windows\inf\agp.PNF
DEL /F /Q Windows\inf\arc.PNF
DEL /F /Q Windows\inf\atiilhag.PNF
DEL /F /Q Windows\inf\avc.PNF
DEL /F /Q Windows\inf\bth.PNF
DEL /F /Q Windows\inf\cpu.PNF
DEL /F /Q Windows\inf\ehstorpwddrv.PNF
DEL /F /Q Windows\inf\hal.PNF
DEL /F /Q Windows\inf\hidirkbd.PNF
DEL /F /Q Windows\inf\mdmcxpv6.PNF
DEL /F /Q Windows\inf\mdmetech.PNF
DEL /F /Q Windows\inf\mdmmoto1.PNF
DEL /F /Q Windows\inf\mdmnis1u.PNF
DEL /F /Q Windows\inf\mdmnis2u.PNF
DEL /F /Q Windows\inf\mdmnis3t.PNF
DEL /F /Q Windows\inf\mdmnis5t.PNF
DEL /F /Q Windows\inf\mdmnttd6.PNF
DEL /F /Q Windows\inf\mdmnttp2.PNF
DEL /F /Q Windows\inf\mdmracal.PNF
DEL /F /Q Windows\inf\mdmsupr3.PNF
DEL /F /Q Windows\inf\mdmusrk1.PNF
DEL /F /Q Windows\inf\netbvbda.PNF
DEL /F /Q Windows\inf\blbdrive.PNF
DEL /F /Q Windows\inf\brmfcmdm.PNF
DEL /F /Q Windows\inf\brmfcumd.PNF
DEL /F /Q Windows\inf\brmfcwia.PNF
DEL /F /Q Windows\inf\hdaudbus.PNF
DEL /F /Q Windows\inf\mdmbtmdm.PNF
DEL /F /Q Windows\inf\mdmcodex.PNF
DEL /F /Q Windows\inf\mdmeiger.PNF
DEL /F /Q Windows\inf\mdmhandy.PNF
DEL /F /Q Windows\inf\mdmiodat.PNF
DEL /F /Q Windows\inf\mdmnokia.PNF
DEL /F /Q Windows\inf\modemcsa.PNF
DEL /F /Q Windows\inf\netevbda.PNF
DEL /F /Q Windows\inf\ph6xib64c0.PNF
DEL /F /Q Windows\inf\ph6xib64c1.PNF
DEL /F /Q Windows\inf\sti.PNF
DEL /F /Q Windows\inf\tpm.PNF
DEL /F /Q Windows\inf\circlass.PNF
DEL /F /Q Windows\inf\cxfalcon_ibv64.PNF
DEL /F /Q Windows\inf\cxfalpal_ibv64.PNF
DEL /F /Q Windows\inf\digitalmediadevice.PNF
DEL /F /Q Windows\inf\gameport.PNF
DEL /F /Q Windows\inf\lsi_scsi.PNF
DEL /F /Q Windows\inf\mdmairte.PNF
DEL /F /Q Windows\inf\mdmaiwat.PNF
DEL /F /Q Windows\inf\mdmcommu.PNF
DEL /F /Q Windows\inf\mdmdgitn.PNF
DEL /F /Q Windows\inf\mdmgatew.PNF
DEL /F /Q Windows\inf\mdmhayes.PNF
DEL /F /Q Windows\inf\mdminfot.PNF
DEL /F /Q Windows\inf\mdmirmdm.PNF
DEL /F /Q Windows\inf\mdmlasat.PNF
DEL /F /Q Windows\inf\mdmlasno.PNF
DEL /F /Q Windows\inf\mdmmhzel.PNF
DEL /F /Q Windows\inf\mdmminij.PNF
DEL /F /Q Windows\inf\mtconfig.PNF
DEL /F /Q Windows\inf\netbxnda.PNF
DEL /F /Q Windows\inf\v_mscdsc.PNF
DEL /F /Q Windows\inf\wdma_usb.PNF
DEL /F /Q Windows\inf\wdmaudio.PNF
DEL /F /Q Windows\inf\brmfcsto.PNF
DEL /F /Q Windows\inf\brmfport.PNF
DEL /F /Q Windows\inf\bthprint.PNF
DEL /F /Q Windows\inf\flpydisk.PNF
DEL /F /Q Windows\inf\kscaptur.PNF
DEL /F /Q Windows\inf\ksfilter.PNF
DEL /F /Q Windows\inf\mdmcrtix.PNF
DEL /F /Q Windows\inf\mdmlucnt.PNF
DEL /F /Q Windows\inf\mdmmetri.PNF
DEL /F /Q Windows\inf\mdmneuhs.PNF
DEL /F /Q Windows\inf\mdmnttme.PNF
DEL /F /Q Windows\inf\mdmpsion.PNF
DEL /F /Q Windows\inf\mdmsmart.PNF
DEL /F /Q Windows\inf\mdmsupra.PNF
DEL /F /Q Windows\inf\mdmtexas.PNF
DEL /F /Q Windows\inf\mdmusrgl.PNF
DEL /F /Q Windows\inf\net8187bv64.PNF
DEL /F /Q Windows\inf\net8187se64.PNF
DEL /F /Q Windows\inf\netrndis.PNF
DEL /F /Q Windows\inf\rndiscmp.PNF
DEL /F /Q Windows\inf\scrawpdo.PNF
DEL /F /Q Windows\inf\smartcrd.PNF
DEL /F /Q Windows\inf\transfercable.PNF
DEL /F /Q Windows\inf\usbvideo.PNF
DEL /F /Q Windows\inf\cxraptor_philipstuv1236d_ibv64.PNF
DEL /F /Q Windows\inf\dot4.PNF
DEL /F /Q Windows\inf\mcx2.PNF
DEL /F /Q Windows\inf\mdmkortx.PNF
DEL /F /Q Windows\inf\mdmmhrtz.PNF
DEL /F /Q Windows\inf\mdmmotou.PNF
DEL /F /Q Windows\inf\mdmnttte.PNF
DEL /F /Q Windows\inf\mdmsonyu.PNF
DEL /F /Q Windows\inf\mdmsuprv.PNF
DEL /F /Q Windows\inf\mdmusrsp.PNF
DEL /F /Q Windows\inf\mdmzyxel.PNF
DEL /F /Q Windows\inf\mdmzyxlg.PNF
DEL /F /Q Windows\inf\multiprt.PNF
DEL /F /Q Windows\inf\netathrx.PNF
DEL /F /Q Windows\inf\nulhpopr.PNF
DEL /F /Q Windows\inf\sbp2.PNF
DEL /F /Q Windows\inf\stexstor.PNF
DEL /F /Q Windows\inf\usbprint.PNF
DEL /F /Q Windows\inf\wpdmtphw.PNF
DEL /F /Q Windows\inf\wsdprint.PNF
DEL /F /Q Windows\inf\wsdscdrv.PNF
DEL /F /Q Windows\inf\averfx2hbh826d_noaverir_x64.PNF
DEL /F /Q Windows\inf\averfx2hbtv_x64.PNF
DEL /F /Q Windows\inf\averfx2swtv_x64.PNF
DEL /F /Q Windows\inf\disk.PNF
DEL /F /Q Windows\inf\ehstorcertdrv.PNF
DEL /F /Q Windows\inf\hidir.PNF
DEL /F /Q Windows\inf\igdlh.PNF
DEL /F /Q Windows\inf\image.PNF
DEL /F /Q Windows\inf\mchgr.PNF
DEL /F /Q Windows\inf\mdmke.PNF
DEL /F /Q Windows\inf\mpio.PNF
DEL /F /Q Windows\inf\msdv.PNF
DEL /F /Q Windows\inf\qd3x64.PNF
DEL /F /Q Windows\inf\ql2300.PNF
DEL /F /Q Windows\inf\ricoh.PNF
DEL /F /Q Windows\inf\tape.PNF
DEL /F /Q Windows\inf\ts_wpdmtp.PNF
DEL /F /Q Windows\inf\wave.PNF
DEL /F /Q Windows\inf\xnacc.PNF
DEL /F /Q Windows\inf\adpu320.PNF
DEL /F /Q Windows\inf\bthmtpenum.PNF
DEL /F /Q Windows\inf\iirsp.PNF
DEL /F /Q Windows\inf\iscsi.PNF
DEL /F /Q Windows\inf\mdmar1.PNF
DEL /F /Q Windows\inf\mdmdp2.PNF
DEL /F /Q Windows\inf\mdmfj2.PNF
DEL /F /Q Windows\inf\mdmpn1.PNF
DEL /F /Q Windows\inf\mdmpp.PNF
DEL /F /Q Windows\inf\mdmti.PNF
DEL /F /Q Windows\inf\mdmvv.PNF
DEL /F /Q Windows\inf\msdsm.PNF
DEL /F /Q Windows\inf\net8185.PNF
DEL /F /Q Windows\inf\netg664.PNF
DEL /F /Q Windows\inf\nfrd960.PNF
DEL /F /Q Windows\inf\nv_lh.PNF
DEL /F /Q Windows\inf\ql40xx.PNF
DEL /F /Q Windows\inf\sdbus.PNF
DEL /F /Q Windows\inf\ts_generic.PNF
DEL /F /Q Windows\inf\vhdmp.PNF
DEL /F /Q Windows\inf\wceisvista.PNF
DEL /F /Q Windows\inf\windowssideshowenhanceddriver.PNF
DEL /F /Q Windows\inf\wpdfs.PNF
DEL /F /Q Windows\inf\amdsbs.PNF
DEL /F /Q Windows\inf\angel64.PNF
DEL /F /Q Windows\inf\arcsas.PNF
DEL /F /Q Windows\inf\bthpan.PNF
DEL /F /Q Windows\inf\hcw72b64.PNF
DEL /F /Q Windows\inf\hcw85b64.PNF
DEL /F /Q Windows\inf\hcw85c64.PNF
DEL /F /Q Windows\inf\hidbth.PNF
DEL /F /Q Windows\inf\hpsamd.PNF
DEL /F /Q Windows\inf\iirsp2.PNF
DEL /F /Q Windows\inf\lsi_fc.PNF
DEL /F /Q Windows\inf\mdm5674a.PNF
DEL /F /Q Windows\inf\mdmadc.PNF
DEL /F /Q Windows\inf\mdmati.PNF
DEL /F /Q Windows\inf\mdmbsb.PNF
DEL /F /Q Windows\inf\mdmc26a.PNF
DEL /F /Q Windows\inf\mdmcdp.PNF
DEL /F /Q Windows\inf\mdmcm28.PNF
DEL /F /Q Windows\inf\mdmgcs.PNF
DEL /F /Q Windows\inf\mdmgen.PNF
DEL /F /Q Windows\inf\mdmmcd.PNF
DEL /F /Q Windows\inf\pcmcia.PNF
DEL /F /Q Windows\inf\ql40xx2.PNF
DEL /F /Q Windows\inf\xcbdav.PNF
DEL /F /Q Windows\inf\avmx64c.PNF
DEL /F /Q Windows\inf\mdmarn.PNF
DEL /F /Q Windows\inf\mdmaus.PNF
DEL /F /Q Windows\inf\mdmcpq.PNF
DEL /F /Q Windows\inf\mdmcpv.PNF
DEL /F /Q Windows\inf\mdmdsi.PNF
DEL /F /Q Windows\inf\mdmgsm.PNF
DEL /F /Q Windows\inf\mdmmct.PNF
DEL /F /Q Windows\inf\mdmmod.PNF
DEL /F /Q Windows\inf\mdmosi.PNF
DEL /F /Q Windows\inf\mdmpin.PNF
DEL /F /Q Windows\inf\mdmtdk.PNF
DEL /F /Q Windows\inf\mdmx5560.PNF
DEL /F /Q Windows\inf\megasr.PNF
DEL /F /Q Windows\inf\msclmd.PNF
DEL /F /Q Windows\inf\mstape.PNF
DEL /F /Q Windows\inf\netimm.PNF
DEL /F /Q Windows\inf\netk57a.PNF
DEL /F /Q Windows\inf\nvraid.PNF
DEL /F /Q Windows\inf\tdibth.PNF
DEL /F /Q Windows\inf\usbcir.PNF
DEL /F /Q Windows\inf\netr7364.PNF
DEL /F /Q Windows\inf\netip6.PNF
DEL /F /Q Windows\inf\nettcpip.PNF
DEL /F /Q Windows\inf\netnb.PNF
DEL /F /Q Windows\inf\netmscli.PNF
DEL /F /Q Windows\inf\netpacer.PNF
DEL /F /Q Windows\inf\ndiscap.PNF
DEL /F /Q Windows\inf\netnwifi.PNF
DEL /F /Q Windows\inf\mdmirmdm.inf
DEL /F /Q Windows\inf\mdmnokia.inf
DEL /F /Q Windows\inf\wiabr00a.inf
DEL /F /Q Windows\inf\wiabr002.inf
DEL /F /Q Windows\inf\wiabr004.inf
DEL /F /Q Windows\inf\wiabr005.inf
DEL /F /Q Windows\inf\wiabr006.inf
DEL /F /Q Windows\inf\wiabr007.inf
DEL /F /Q Windows\inf\wiabr008.inf
DEL /F /Q Windows\inf\wiabr009.inf
DEL /F /Q Windows\inf\wiaca00a.inf
DEL /F /Q Windows\inf\wiaca00b.inf
DEL /F /Q Windows\inf\wiaca00c.inf
DEL /F /Q Windows\inf\wiaca00d.inf
DEL /F /Q Windows\inf\wiaca00e.inf
DEL /F /Q Windows\inf\wiaca00f.inf
DEL /F /Q Windows\inf\wiaca00i.inf
DEL /F /Q Windows\inf\wiacn001.inf
DEL /F /Q Windows\inf\wiaep002.inf
DEL /F /Q Windows\inf\wiaep003.inf
DEL /F /Q Windows\inf\wiahp001.inf
DEL /F /Q Windows\inf\wiaky002.inf
DEL /F /Q Windows\inf\wialx002.inf
DEL /F /Q Windows\inf\wialx003.inf
DEL /F /Q Windows\inf\wialx004.inf
DEL /F /Q Windows\inf\wialx005.inf
DEL /F /Q Windows\inf\wialx006.inf
DEL /F /Q Windows\inf\wiasa002.inf
DEL /F /Q Windows\inf\wiaxx002.inf
DEL /F /Q Windows\inf\igdlh.inf
DEL /F /Q Windows\inf\nv_lh.inf
DEL /F /Q Windows\inf\ph3xibc0.inf
DEL /F /Q Windows\inf\ph3xibc1.inf
DEL /F /Q Windows\inf\ph3xibc2.inf
DEL /F /Q Windows\inf\ph3xibc3.inf
DEL /F /Q Windows\inf\ph3xibc4.inf
DEL /F /Q Windows\inf\ph3xibc5.inf
DEL /F /Q Windows\inf\ph3xibc6.inf
DEL /F /Q Windows\inf\ph3xibc7.inf
DEL /F /Q Windows\inf\ph3xibc8.inf
DEL /F /Q Windows\inf\ph3xibc9.inf
DEL /F /Q Windows\inf\ph3xibc10.inf
DEL /F /Q Windows\inf\ph3xibc11.inf
DEL /F /Q Windows\inf\ph3xibc12.inf
DEL /F /Q Windows\inf\ph6xib64c0.inf
DEL /F /Q Windows\inf\ph6xib64c1.inf
DEL /F /Q Windows\inf\mdmgl001.inf
DEL /F /Q Windows\inf\mdmgl002.inf
DEL /F /Q Windows\inf\mdmgl003.inf
DEL /F /Q Windows\inf\mdmgl004.inf
DEL /F /Q Windows\inf\mdmgl005.inf
DEL /F /Q Windows\inf\mdmgl006.inf
DEL /F /Q Windows\inf\mdmgl007.inf
DEL /F /Q Windows\inf\mdmgl008.inf
DEL /F /Q Windows\inf\mdmgl009.inf
DEL /F /Q Windows\inf\mdmgl010.inf
DEL /F /Q Windows\inf\mdm3com.inf
DEL /F /Q Windows\inf\mdm5674a.inf
DEL /F /Q Windows\inf\mdmadc.inf
DEL /F /Q Windows\inf\mdmairte.inf
DEL /F /Q Windows\inf\mdmaiwa.inf
DEL /F /Q Windows\inf\mdmaiwa3.inf
DEL /F /Q Windows\inf\mdmaiwa4.inf
DEL /F /Q Windows\inf\mdmaiwa5.inf
DEL /F /Q Windows\inf\mdmaiwat.inf
DEL /F /Q Windows\inf\mdmar1.inf
DEL /F /Q Windows\inf\mdmarch.inf
DEL /F /Q Windows\inf\mdmarn.inf
DEL /F /Q Windows\inf\mdmati.inf
DEL /F /Q Windows\inf\mdmbr00a.inf
DEL /F /Q Windows\inf\mdmbr002.inf
DEL /F /Q Windows\inf\mdmbr004.inf
DEL /F /Q Windows\inf\mdmbr005.inf
DEL /F /Q Windows\inf\mdmbr006.inf
DEL /F /Q Windows\inf\mdmbr007.inf
DEL /F /Q Windows\inf\mdmbr008.inf
DEL /F /Q Windows\inf\mdmatm2k.inf
DEL /F /Q Windows\inf\mdmaus.inf
DEL /F /Q Windows\inf\mdmboca.inf
DEL /F /Q Windows\inf\mdmbsb.inf
DEL /F /Q Windows\inf\mdmbug3.inf
DEL /F /Q Windows\inf\mdmbw561.inf
DEL /F /Q Windows\inf\mdmc26a.inf
DEL /F /Q Windows\inf\mdmcdp.inf
DEL /F /Q Windows\inf\mdmcm28.inf
DEL /F /Q Windows\inf\mdmcodex.inf
DEL /F /Q Windows\inf\mdmcom1.inf
DEL /F /Q Windows\inf\mdmcommu.inf
DEL /F /Q Windows\inf\mdmcomp.inf
DEL /F /Q Windows\inf\mdmcpq2.inf
DEL /F /Q Windows\inf\mdmcpv.inf
DEL /F /Q Windows\inf\mdmcrtix.inf
DEL /F /Q Windows\inf\mdmdcm5.inf
DEL /F /Q Windows\inf\mdmdcm6.inf
DEL /F /Q Windows\inf\mdmdf56f.inf
DEL /F /Q Windows\inf\mdmdgitn.inf
DEL /F /Q Windows\inf\mdmdp2.inf
DEL /F /Q Windows\inf\mdmdsi.inf
DEL /F /Q Windows\inf\mdmdyna.inf
DEL /F /Q Windows\inf\mdmeiger.inf
DEL /F /Q Windows\inf\mdmelsa.inf
DEL /F /Q Windows\inf\mdmeric.inf
DEL /F /Q Windows\inf\mdmeric2.inf
DEL /F /Q Windows\inf\mdmetech.inf
DEL /F /Q Windows\inf\mdmfj2.inf
DEL /F /Q Windows\inf\mdmgatew.inf
DEL /F /Q Windows\inf\mdmgcs.inf
DEL /F /Q Windows\inf\mdmgsm.inf
DEL /F /Q Windows\inf\mdmhaeu.inf
DEL /F /Q Windows\inf\mdmhandy.inf
DEL /F /Q Windows\inf\mdmhay2.inf
DEL /F /Q Windows\inf\mdmhayes.inf
DEL /F /Q Windows\inf\mdminfot.inf
DEL /F /Q Windows\inf\mdmiodat.inf
DEL /F /Q Windows\inf\mdmisdn.inf
DEL /F /Q Windows\inf\mdmjf56e.inf
DEL /F /Q Windows\inf\mdmke.inf
DEL /F /Q Windows\inf\mdmkortx.inf
DEL /F /Q Windows\inf\mdmlasat.inf
DEL /F /Q Windows\inf\mdmlasno.inf
DEL /F /Q Windows\inf\mdmlucnt.inf
DEL /F /Q Windows\inf\mdmmc288.inf
DEL /F /Q Windows\inf\mdmmcd.inf
DEL /F /Q Windows\inf\mdmmcom.inf
DEL /F /Q Windows\inf\mdmmct.inf
DEL /F /Q Windows\inf\mdmmega.inf
DEL /F /Q Windows\inf\mdmmetri.inf
DEL /F /Q Windows\inf\mdmmhrtz.inf
DEL /F /Q Windows\inf\mdmmhzel.inf
DEL /F /Q Windows\inf\mdmminij.inf
DEL /F /Q Windows\inf\mdmmod.inf
DEL /F /Q Windows\inf\mdmmoto1.inf
DEL /F /Q Windows\inf\mdmmotou.inf
DEL /F /Q Windows\inf\mdmmts.inf
DEL /F /Q Windows\inf\mdmneuhs.inf
DEL /F /Q Windows\inf\mdmnis3t.inf
DEL /F /Q Windows\inf\mdmnis5t.inf
DEL /F /Q Windows\inf\mdmnova.inf
DEL /F /Q Windows\inf\mdmntt1.inf
DEL /F /Q Windows\inf\mdmnttd2.inf
DEL /F /Q Windows\inf\mdmnttd6.inf
DEL /F /Q Windows\inf\mdmnttme.inf
DEL /F /Q Windows\inf\mdmnttp.inf
DEL /F /Q Windows\inf\mdmnttp2.inf
DEL /F /Q Windows\inf\mdmnttte.inf
DEL /F /Q Windows\inf\mdmolic.inf
DEL /F /Q Windows\inf\mdmomrn3.inf
DEL /F /Q Windows\inf\mdmoptn.inf
DEL /F /Q Windows\inf\mdmosi.inf
DEL /F /Q Windows\inf\mdmpace.inf
DEL /F /Q Windows\inf\mdmpenr.inf
DEL /F /Q Windows\inf\mdmpin.inf
DEL /F /Q Windows\inf\mdmpn1.inf
DEL /F /Q Windows\inf\mdmpp.inf
DEL /F /Q Windows\inf\mdmpsion.inf
DEL /F /Q Windows\inf\mdmracal.inf
DEL /F /Q Windows\inf\mdmrock.inf
DEL /F /Q Windows\inf\mdmrock3.inf
DEL /F /Q Windows\inf\mdmrock4.inf
DEL /F /Q Windows\inf\mdmrock5.inf
DEL /F /Q Windows\inf\mdmsier.inf
DEL /F /Q Windows\inf\mdmsii64.inf
DEL /F /Q Windows\inf\mdmsmart.inf
DEL /F /Q Windows\inf\mdmsonyu.inf
DEL /F /Q Windows\inf\mdmsun1.inf
DEL /F /Q Windows\inf\mdmsun2.inf
DEL /F /Q Windows\inf\mdmsupr3.inf
DEL /F /Q Windows\inf\mdmsupra.inf
DEL /F /Q Windows\inf\mdmsuprv.inf
DEL /F /Q Windows\inf\mdmtdk.inf
DEL /F /Q Windows\inf\mdmtdkj2.inf
DEL /F /Q Windows\inf\mdmtdkj3.inf
DEL /F /Q Windows\inf\mdmtdkj4.inf
DEL /F /Q Windows\inf\mdmtdkj5.inf
DEL /F /Q Windows\inf\mdmtdkj6.inf
DEL /F /Q Windows\inf\mdmtdkj7.inf
DEL /F /Q Windows\inf\mdmtexas.inf
DEL /F /Q Windows\inf\mdmti.inf
DEL /F /Q Windows\inf\mdmtkr.inf
DEL /F /Q Windows\inf\mdmtron.inf
DEL /F /Q Windows\inf\mdmusrf.inf
DEL /F /Q Windows\inf\mdmusrg.inf
DEL /F /Q Windows\inf\mdmusrgl.inf
DEL /F /Q Windows\inf\mdmusrk1.inf
DEL /F /Q Windows\inf\mdmusrsp.inf
DEL /F /Q Windows\inf\mdmvdot.inf
DEL /F /Q Windows\inf\mdmvv.inf
DEL /F /Q Windows\inf\mdmwhql0.inf
DEL /F /Q Windows\inf\mdmagm64.inf
DEL /F /Q Windows\inf\mdmags64.inf
DEL /F /Q Windows\inf\mdmmot64.inf
DEL /F /Q Windows\inf\mdmx5560.inf
DEL /F /Q Windows\inf\mdmzoom.inf
DEL /F /Q Windows\inf\mdmzyp.inf
DEL /F /Q Windows\inf\mdmzyxel.inf
DEL /F /Q Windows\inf\mdmzyxlg.inf
DEL /F /Q Windows\inf\mdmcxhv6.inf
DEL /F /Q Windows\inf\mdmcxpv6.inf
DEL /F /Q Windows\inf\prnbr00a.inf
DEL /F /Q Windows\inf\prnbr002.inf
DEL /F /Q Windows\inf\prnbr003.inf
DEL /F /Q Windows\inf\prnbr004.inf
DEL /F /Q Windows\inf\prnbr005.inf
DEL /F /Q Windows\inf\prnbr006.inf
DEL /F /Q Windows\inf\prnbr007.inf
DEL /F /Q Windows\inf\prnbr008.inf
DEL /F /Q Windows\inf\prnbr009.inf
DEL /F /Q Windows\inf\prnca00a.inf
DEL /F /Q Windows\inf\prnca00b.inf
DEL /F /Q Windows\inf\prnca00c.inf
DEL /F /Q Windows\inf\prnca00d.inf
DEL /F /Q Windows\inf\prnca00e.inf
DEL /F /Q Windows\inf\prnca00f.inf
DEL /F /Q Windows\inf\prnca00g.inf
DEL /F /Q Windows\inf\prnca00h.inf
DEL /F /Q Windows\inf\prnca00i.inf
DEL /F /Q Windows\inf\prnca00x.inf
DEL /F /Q Windows\inf\prnca00y.inf
DEL /F /Q Windows\inf\prnca00z.inf
DEL /F /Q Windows\inf\prnca003.inf
DEL /F /Q Windows\inf\prnep00b.inf
DEL /F /Q Windows\inf\prnep00c.inf
DEL /F /Q Windows\inf\prnep00d.inf
DEL /F /Q Windows\inf\prnep00e.inf
DEL /F /Q Windows\inf\prnep00f.inf
DEL /F /Q Windows\inf\prnep00g.inf
DEL /F /Q Windows\inf\prnep00l.inf
DEL /F /Q Windows\inf\prnep003.inf
DEL /F /Q Windows\inf\prnep004.inf
DEL /F /Q Windows\inf\prnfx002.inf
DEL /F /Q Windows\inf\prngt002.inf
DEL /F /Q Windows\inf\prngt003.inf
DEL /F /Q Windows\inf\prngt004.inf
DEL /F /Q Windows\inf\prnhp002.inf
DEL /F /Q Windows\inf\prnhp003.inf
DEL /F /Q Windows\inf\prnhp004.inf
DEL /F /Q Windows\inf\prnhp005.inf
DEL /F /Q Windows\inf\prnin002.inf
DEL /F /Q Windows\inf\prnin003.inf
DEL /F /Q Windows\inf\prnin004.inf
DEL /F /Q Windows\inf\prnkm002.inf
DEL /F /Q Windows\inf\prnkm003.inf
DEL /F /Q Windows\inf\prnkm004.inf
DEL /F /Q Windows\inf\prnkm005.inf
DEL /F /Q Windows\inf\prnky002.inf
DEL /F /Q Windows\inf\prnky003.inf
DEL /F /Q Windows\inf\prnky004.inf
DEL /F /Q Windows\inf\prnky005.inf
DEL /F /Q Windows\inf\prnky006.inf
DEL /F /Q Windows\inf\prnky007.inf
DEL /F /Q Windows\inf\prnky008.inf
DEL /F /Q Windows\inf\prnky009.inf
DEL /F /Q Windows\inf\prnle002.inf
DEL /F /Q Windows\inf\prnle003.inf
DEL /F /Q Windows\inf\prnle004.inf
DEL /F /Q Windows\inf\prnlx00a.inf
DEL /F /Q Windows\inf\prnlx00b.inf
DEL /F /Q Windows\inf\prnlx00c.inf
DEL /F /Q Windows\inf\prnlx00d.inf
DEL /F /Q Windows\inf\prnlx00e.inf
DEL /F /Q Windows\inf\prnlx00v.inf
DEL /F /Q Windows\inf\prnlx00w.inf
DEL /F /Q Windows\inf\prnlx00x.inf
DEL /F /Q Windows\inf\prnlx00y.inf
DEL /F /Q Windows\inf\prnlx00z.inf
DEL /F /Q Windows\inf\prnlx002.inf
DEL /F /Q Windows\inf\prnlx003.inf
DEL /F /Q Windows\inf\prnlx004.inf
DEL /F /Q Windows\inf\prnlx005.inf
DEL /F /Q Windows\inf\prnlx006.inf
DEL /F /Q Windows\inf\prnlx007.inf
DEL /F /Q Windows\inf\prnlx008.inf
DEL /F /Q Windows\inf\prnlx009.inf
DEL /F /Q Windows\inf\prnnr002.inf
DEL /F /Q Windows\inf\prnnr003.inf
DEL /F /Q Windows\inf\prnnr004.inf
DEL /F /Q Windows\inf\prnod002.inf
DEL /F /Q Windows\inf\prnok002.inf
DEL /F /Q Windows\inf\prnrc00a.inf
DEL /F /Q Windows\inf\prnrc00b.inf
DEL /F /Q Windows\inf\prnrc00c.inf
DEL /F /Q Windows\inf\prnrc002.inf
DEL /F /Q Windows\inf\prnrc003.inf
DEL /F /Q Windows\inf\prnrc004.inf
DEL /F /Q Windows\inf\prnrc005.inf
DEL /F /Q Windows\inf\prnrc006.inf
DEL /F /Q Windows\inf\prnrc007.inf
DEL /F /Q Windows\inf\prnsa002.inf
DEL /F /Q Windows\inf\prnsh002.inf
DEL /F /Q Windows\inf\prnso002.inf
DEL /F /Q Windows\inf\prnsv002.inf
DEL /F /Q Windows\inf\prnsv003.inf
DEL /F /Q Windows\inf\prnsv004.inf
DEL /F /Q Windows\inf\prnts002.inf
DEL /F /Q Windows\inf\prnts003.inf
DEL /F /Q Windows\inf\prnxx002.inf
DEL /F /Q Windows\inf\atiilhag.inf
DEL /F /Q Windows\inf\ndisuio.PNF
DEL /F /Q Windows\inf\netavpnt.PNF
DEL /F /Q Windows\inf\netrass.PNF
DEL /F /Q Windows\inf\netrast.PNF
DEL /F /Q Windows\inf\netserv.PNF
DEL /F /Q Windows\inf\netsstpt.PNF
DEL /F /Q Windows\inf\TsUsbHubFilter.PNF
DEL /F /Q Windows\inf\cdrom.PNF
DEL /F /Q Windows\inf\input.PNF
DEL /F /Q Windows\inf\ipmidrv.PNF
DEL /F /Q Windows\inf\machine.PNF
DEL /F /Q Windows\inf\mshdc.PNF
DEL /F /Q Windows\inf\usb.PNF
DEL /F /Q Windows\inf\usbport.PNF
DEL /F /Q Windows\inf\volume.PNF
DEL /F /Q Windows\inf\netavpna.PNF
DEL /F /Q Windows\inf\netrasa.PNF
DEL /F /Q Windows\inf\netsstpa.PNF
DEL /F /Q Windows\inf\acpi.PNF
DEL /F /Q Windows\inf\keyboard.PNF
DEL /F /Q Windows\inf\umbus.PNF
DEL /F /Q Windows\inf\setupapi.app.log
DEL /F /Q Windows\inf\prnok652.inf
DEL /F /Q Windows\inf\setupapi.offline.log
del /a /f /q /s "Windows\inf\*.pnf"
pause