DEL /F /Q I:\Windows\inf\af9035bda.inf
DEL /F /Q I:\Windows\inf\angel.inf
DEL /F /Q I:\Windows\inf\angel2.inf
DEL /F /Q I:\Windows\inf\angelusb.inf
DEL /F /Q I:\Windows\inf\atiilhag.inf
DEL /F /Q I:\Windows\inf\atiriolh.inf
DEL /F /Q I:\Windows\inf\averfx2h826d_noaverir.inf
DEL /F /Q I:\Windows\inf\averfx2hbtv.inf
DEL /F /Q I:\Windows\inf\averfx2swtv.inf
DEL /F /Q I:\Windows\inf\averfx2swtv_noavin.inf
DEL /F /Q I:\Windows\inf\averhbh826_noaverir.inf
DEL /F /Q I:\Windows\inf\brmfcmdm.inf
DEL /F /Q I:\Windows\inf\brmfcwia.inf
DEL /F /Q I:\Windows\inf\cxfalcon_ibv32.inf
DEL /F /Q I:\Windows\inf\cxfalpal_ibv32.inf
DEL /F /Q I:\Windows\inf\cxraptor_fm1216mk5_ibv32.inf
DEL /F /Q I:\Windows\inf\cxraptor_fm1236mk5_ibv32.inf
DEL /F /Q I:\Windows\inf\cxraptor_philipstuv1236d_ibv32.inf
DEL /F /Q I:\Windows\inf\faxca003.inf
DEL /F /Q I:\Windows\inf\faxcn001.inf
DEL /F /Q I:\Windows\inf\faxcn002.inf
DEL /F /Q I:\Windows\inf\hcw72bda.inf
DEL /F /Q I:\Windows\inf\hcw85bda.inf
DEL /F /Q I:\Windows\inf\hpoa1sd.inf
DEL /F /Q I:\Windows\inf\hpoa1so.inf
DEL /F /Q I:\Windows\inf\hpoa1ss.inf
DEL /F /Q I:\Windows\inf\igdlh.inf
DEL /F /Q I:\Windows\inf\mdm3com.inf
DEL /F /Q I:\Windows\inf\mdm5674a.inf
DEL /F /Q I:\Windows\inf\mdmadc.inf
DEL /F /Q I:\Windows\inf\mdmagrm.inf
DEL /F /Q I:\Windows\inf\mdmagrs.inf
DEL /F /Q I:\Windows\inf\mdmairte.inf
DEL /F /Q I:\Windows\inf\mdmaiwa.inf
DEL /F /Q I:\Windows\inf\mdmaiwa3.inf
DEL /F /Q I:\Windows\inf\mdmaiwa4.inf
DEL /F /Q I:\Windows\inf\mdmaiwa5.inf
DEL /F /Q I:\Windows\inf\mdmaiwat.inf
DEL /F /Q I:\Windows\inf\mdmar1.inf
DEL /F /Q I:\Windows\inf\mdmarch.inf
DEL /F /Q I:\Windows\inf\mdmarn.inf
DEL /F /Q I:\Windows\inf\mdmati.inf
DEL /F /Q I:\Windows\inf\mdmatm2k.inf
DEL /F /Q I:\Windows\inf\mdmaus.inf
DEL /F /Q I:\Windows\inf\mdmboca.inf
DEL /F /Q I:\Windows\inf\mdmbr00a.inf
DEL /F /Q I:\Windows\inf\mdmbr002.inf
DEL /F /Q I:\Windows\inf\mdmbr004.inf
DEL /F /Q I:\Windows\inf\mdmbr005.inf
DEL /F /Q I:\Windows\inf\mdmbr006.inf
DEL /F /Q I:\Windows\inf\mdmbr007.inf
DEL /F /Q I:\Windows\inf\mdmbr008.inf
DEL /F /Q I:\Windows\inf\mdmbsb.inf
DEL /F /Q I:\Windows\inf\mdmbug3.inf
DEL /F /Q I:\Windows\inf\mdmbw561.inf
DEL /F /Q I:\Windows\inf\mdmc26a.inf
DEL /F /Q I:\Windows\inf\mdmcdp.inf
DEL /F /Q I:\Windows\inf\mdmcm28.inf
DEL /F /Q I:\Windows\inf\mdmcodex.inf
DEL /F /Q I:\Windows\inf\mdmcom1.inf
DEL /F /Q I:\Windows\inf\mdmcommu.inf
DEL /F /Q I:\Windows\inf\mdmcomp.inf
DEL /F /Q I:\Windows\inf\mdmcpq.inf
DEL /F /Q I:\Windows\inf\mdmcpq2.inf
DEL /F /Q I:\Windows\inf\mdmcpv.inf
DEL /F /Q I:\Windows\inf\mdmcrtix.inf
DEL /F /Q I:\Windows\inf\mdmcxav3.inf
DEL /F /Q I:\Windows\inf\mdmcxhv3.inf
DEL /F /Q I:\Windows\inf\mdmcxpv3.inf
DEL /F /Q I:\Windows\inf\mdmdcm5.inf
DEL /F /Q I:\Windows\inf\mdmdcm6.inf
DEL /F /Q I:\Windows\inf\mdmdf56f.inf
DEL /F /Q I:\Windows\inf\mdmdgitn.inf
DEL /F /Q I:\Windows\inf\mdmdp2.inf
DEL /F /Q I:\Windows\inf\mdmdsi.inf
DEL /F /Q I:\Windows\inf\mdmdyna.inf
DEL /F /Q I:\Windows\inf\mdmeiger.inf
DEL /F /Q I:\Windows\inf\mdmelsa.inf
DEL /F /Q I:\Windows\inf\mdmeric.inf
DEL /F /Q I:\Windows\inf\mdmeric2.inf
DEL /F /Q I:\Windows\inf\mdmetech.inf
DEL /F /Q I:\Windows\inf\mdmfj2.inf
DEL /F /Q I:\Windows\inf\mdmgatew.inf
DEL /F /Q I:\Windows\inf\mdmgcs.inf
DEL /F /Q I:\Windows\inf\mdmgen.inf
DEL /F /Q I:\Windows\inf\mdmgl001.inf
DEL /F /Q I:\Windows\inf\mdmgl002.inf
DEL /F /Q I:\Windows\inf\mdmgl003.inf
DEL /F /Q I:\Windows\inf\mdmgl004.inf
DEL /F /Q I:\Windows\inf\mdmgl005.inf
DEL /F /Q I:\Windows\inf\mdmgl006.inf
DEL /F /Q I:\Windows\inf\mdmgl007.inf
DEL /F /Q I:\Windows\inf\mdmgl008.inf
DEL /F /Q I:\Windows\inf\mdmgl009.inf
DEL /F /Q I:\Windows\inf\mdmgl010.inf
DEL /F /Q I:\Windows\inf\mdmgsm.inf
DEL /F /Q I:\Windows\inf\mdmhaeu.inf
DEL /F /Q I:\Windows\inf\mdmhandy.inf
DEL /F /Q I:\Windows\inf\mdmhay2.inf
DEL /F /Q I:\Windows\inf\mdmhayes.inf
DEL /F /Q I:\Windows\inf\mdminfot.inf
DEL /F /Q I:\Windows\inf\mdmiodat.inf
DEL /F /Q I:\Windows\inf\mdmirmdm.inf
DEL /F /Q I:\Windows\inf\mdmisdn.inf
DEL /F /Q I:\Windows\inf\mdmjf56e.inf
DEL /F /Q I:\Windows\inf\mdmke.inf
DEL /F /Q I:\Windows\inf\mdmkortx.inf
DEL /F /Q I:\Windows\inf\mdmlasat.inf
DEL /F /Q I:\Windows\inf\mdmlasno.inf
DEL /F /Q I:\Windows\inf\mdmlucnt.inf
DEL /F /Q I:\Windows\inf\mdmmc288.inf
DEL /F /Q I:\Windows\inf\mdmmcd.inf
DEL /F /Q I:\Windows\inf\mdmmcom.inf
DEL /F /Q I:\Windows\inf\mdmmct.inf
DEL /F /Q I:\Windows\inf\mdmmega.inf
DEL /F /Q I:\Windows\inf\mdmmetri.inf
DEL /F /Q I:\Windows\inf\mdmmhrtz.inf
DEL /F /Q I:\Windows\inf\mdmmhzel.inf
DEL /F /Q I:\Windows\inf\mdmminij.inf
DEL /F /Q I:\Windows\inf\mdmmod.inf
DEL /F /Q I:\Windows\inf\mdmmoto1.inf
DEL /F /Q I:\Windows\inf\mdmmotou.inf
DEL /F /Q I:\Windows\inf\mdmmotsm.inf
DEL /F /Q I:\Windows\inf\mdmmts.inf
DEL /F /Q I:\Windows\inf\mdmneuhs.inf
DEL /F /Q I:\Windows\inf\mdmnis1u.inf
DEL /F /Q I:\Windows\inf\mdmnis2u.inf
DEL /F /Q I:\Windows\inf\mdmnis3t.inf
DEL /F /Q I:\Windows\inf\mdmnis5t.inf
DEL /F /Q I:\Windows\inf\mdmnokia.inf
DEL /F /Q I:\Windows\inf\mdmnova.inf
DEL /F /Q I:\Windows\inf\mdmntt1.inf
DEL /F /Q I:\Windows\inf\mdmnttd2.inf
DEL /F /Q I:\Windows\inf\mdmnttd6.inf
DEL /F /Q I:\Windows\inf\mdmnttme.inf
DEL /F /Q I:\Windows\inf\mdmnttp.inf
DEL /F /Q I:\Windows\inf\mdmnttp2.inf
DEL /F /Q I:\Windows\inf\mdmnttte.inf
DEL /F /Q I:\Windows\inf\mdmolic.inf
DEL /F /Q I:\Windows\inf\mdmomrn3.inf
DEL /F /Q I:\Windows\inf\mdmoptn.inf
DEL /F /Q I:\Windows\inf\mdmosi.inf
DEL /F /Q I:\Windows\inf\mdmpace.inf
DEL /F /Q I:\Windows\inf\mdmpenr.inf
DEL /F /Q I:\Windows\inf\mdmpin.inf
DEL /F /Q I:\Windows\inf\mdmpn1.inf
DEL /F /Q I:\Windows\inf\mdmpp.inf
DEL /F /Q I:\Windows\inf\mdmpsion.inf
DEL /F /Q I:\Windows\inf\mdmracal.inf
DEL /F /Q I:\Windows\inf\mdmrock.inf
DEL /F /Q I:\Windows\inf\mdmrock3.inf
DEL /F /Q I:\Windows\inf\mdmrock4.inf
DEL /F /Q I:\Windows\inf\mdmrock5.inf
DEL /F /Q I:\Windows\inf\mdmsier.inf
DEL /F /Q I:\Windows\inf\mdmsii64.inf
DEL /F /Q I:\Windows\inf\mdmsmart.inf
DEL /F /Q I:\Windows\inf\mdmsonyu.inf
DEL /F /Q I:\Windows\inf\mdmsun1.inf
DEL /F /Q I:\Windows\inf\mdmsun2.inf
DEL /F /Q I:\Windows\inf\mdmsupr3.inf
DEL /F /Q I:\Windows\inf\mdmsupra.inf
DEL /F /Q I:\Windows\inf\mdmsuprv.inf
DEL /F /Q I:\Windows\inf\mdmtdk.inf
DEL /F /Q I:\Windows\inf\mdmtdkj2.inf
DEL /F /Q I:\Windows\inf\mdmtdkj3.inf
DEL /F /Q I:\Windows\inf\mdmtdkj4.inf
DEL /F /Q I:\Windows\inf\mdmtdkj5.inf
DEL /F /Q I:\Windows\inf\mdmtdkj6.inf
DEL /F /Q I:\Windows\inf\mdmtdkj7.inf
DEL /F /Q I:\Windows\inf\mdmtexas.inf
DEL /F /Q I:\Windows\inf\mdmti.inf
DEL /F /Q I:\Windows\inf\mdmtkr.inf
DEL /F /Q I:\Windows\inf\mdmtron.inf
DEL /F /Q I:\Windows\inf\mdmusrf.inf
DEL /F /Q I:\Windows\inf\mdmusrg.inf
DEL /F /Q I:\Windows\inf\mdmusrgl.inf
DEL /F /Q I:\Windows\inf\mdmusrk1.inf
DEL /F /Q I:\Windows\inf\mdmusrsp.inf
DEL /F /Q I:\Windows\inf\mdmvdot.inf
DEL /F /Q I:\Windows\inf\mdmvv.inf
DEL /F /Q I:\Windows\inf\mdmwhql0.inf
DEL /F /Q I:\Windows\inf\mdmx5560.inf
DEL /F /Q I:\Windows\inf\mdmzoom.inf
DEL /F /Q I:\Windows\inf\mdmzyp.inf
DEL /F /Q I:\Windows\inf\mdmzyxel.inf
DEL /F /Q I:\Windows\inf\mdmzyxlg.inf
DEL /F /Q I:\Windows\inf\nv_lh.inf
DEL /F /Q I:\Windows\inf\ph3xibc0.inf
DEL /F /Q I:\Windows\inf\ph3xibc1.inf
DEL /F /Q I:\Windows\inf\ph3xibc2.inf
DEL /F /Q I:\Windows\inf\ph3xibc3.inf
DEL /F /Q I:\Windows\inf\ph3xibc4.inf
DEL /F /Q I:\Windows\inf\ph3xibc5.inf
DEL /F /Q I:\Windows\inf\ph3xibc6.inf
DEL /F /Q I:\Windows\inf\ph3xibc7.inf
DEL /F /Q I:\Windows\inf\ph3xibc8.inf
DEL /F /Q I:\Windows\inf\ph3xibc9.inf
DEL /F /Q I:\Windows\inf\ph3xibc10.inf
DEL /F /Q I:\Windows\inf\ph3xibc11.inf
DEL /F /Q I:\Windows\inf\ph3xibc12.inf
DEL /F /Q I:\Windows\inf\ph6xib32c0.inf
DEL /F /Q I:\Windows\inf\ph6xib32c1.inf
DEL /F /Q I:\Windows\inf\prnbr00a.inf
DEL /F /Q I:\Windows\inf\prnbr002.inf
DEL /F /Q I:\Windows\inf\prnbr003.inf
DEL /F /Q I:\Windows\inf\prnbr004.inf
DEL /F /Q I:\Windows\inf\prnbr005.inf
DEL /F /Q I:\Windows\inf\prnbr006.inf
DEL /F /Q I:\Windows\inf\prnbr007.inf
DEL /F /Q I:\Windows\inf\prnbr008.inf
DEL /F /Q I:\Windows\inf\prnbr009.inf
DEL /F /Q I:\Windows\inf\prnca00a.inf
DEL /F /Q I:\Windows\inf\prnca00b.inf
DEL /F /Q I:\Windows\inf\prnca00c.inf
DEL /F /Q I:\Windows\inf\prnca00d.inf
DEL /F /Q I:\Windows\inf\prnca00e.inf
DEL /F /Q I:\Windows\inf\prnca00f.inf
DEL /F /Q I:\Windows\inf\prnca00g.inf
DEL /F /Q I:\Windows\inf\prnca00h.inf
DEL /F /Q I:\Windows\inf\prnca00i.inf
DEL /F /Q I:\Windows\inf\prnca00x.inf
DEL /F /Q I:\Windows\inf\prnca00y.inf
DEL /F /Q I:\Windows\inf\prnca00z.inf
DEL /F /Q I:\Windows\inf\prnca003.inf
DEL /F /Q I:\Windows\inf\prnep00a.inf
DEL /F /Q I:\Windows\inf\prnep00b.inf
DEL /F /Q I:\Windows\inf\prnep00c.inf
DEL /F /Q I:\Windows\inf\prnep00d.inf
DEL /F /Q I:\Windows\inf\prnep00e.inf
DEL /F /Q I:\Windows\inf\prnep00f.inf
DEL /F /Q I:\Windows\inf\prnep00g.inf
DEL /F /Q I:\Windows\inf\prnep00l.inf
DEL /F /Q I:\Windows\inf\prnep002.inf
DEL /F /Q I:\Windows\inf\prnep003.inf
DEL /F /Q I:\Windows\inf\prnep004.inf
DEL /F /Q I:\Windows\inf\prnep005.inf
DEL /F /Q I:\Windows\inf\prnep654.inf
DEL /F /Q I:\Windows\inf\prnfx002.inf
DEL /F /Q I:\Windows\inf\prngt002.inf
DEL /F /Q I:\Windows\inf\prngt003.inf
DEL /F /Q I:\Windows\inf\prngt004.inf
DEL /F /Q I:\Windows\inf\prnhp002.inf
DEL /F /Q I:\Windows\inf\prnhp003.inf
DEL /F /Q I:\Windows\inf\prnhp004.inf
DEL /F /Q I:\Windows\inf\prnhp005.inf
DEL /F /Q I:\Windows\inf\prnin002.inf
DEL /F /Q I:\Windows\inf\prnin003.inf
DEL /F /Q I:\Windows\inf\prnin004.inf
DEL /F /Q I:\Windows\inf\prnkm002.inf
DEL /F /Q I:\Windows\inf\prnkm003.inf
DEL /F /Q I:\Windows\inf\prnkm004.inf
DEL /F /Q I:\Windows\inf\prnkm005.inf
DEL /F /Q I:\Windows\inf\prnky002.inf
DEL /F /Q I:\Windows\inf\prnky003.inf
DEL /F /Q I:\Windows\inf\prnky004.inf
DEL /F /Q I:\Windows\inf\prnky005.inf
DEL /F /Q I:\Windows\inf\prnky006.inf
DEL /F /Q I:\Windows\inf\prnky007.inf
DEL /F /Q I:\Windows\inf\prnky008.inf
DEL /F /Q I:\Windows\inf\prnky009.inf
DEL /F /Q I:\Windows\inf\prnle002.inf
DEL /F /Q I:\Windows\inf\prnle003.inf
DEL /F /Q I:\Windows\inf\prnle004.inf
DEL /F /Q I:\Windows\inf\prnlx00a.inf
DEL /F /Q I:\Windows\inf\prnlx00b.inf
DEL /F /Q I:\Windows\inf\prnlx00c.inf
DEL /F /Q I:\Windows\inf\prnlx00d.inf
DEL /F /Q I:\Windows\inf\prnlx00e.inf
DEL /F /Q I:\Windows\inf\prnlx00v.inf
DEL /F /Q I:\Windows\inf\prnlx00w.inf
DEL /F /Q I:\Windows\inf\prnlx00x.inf
DEL /F /Q I:\Windows\inf\prnlx00y.inf
DEL /F /Q I:\Windows\inf\prnlx00z.inf
DEL /F /Q I:\Windows\inf\prnlx002.inf
DEL /F /Q I:\Windows\inf\prnlx003.inf
DEL /F /Q I:\Windows\inf\prnlx004.inf
DEL /F /Q I:\Windows\inf\prnlx005.inf
DEL /F /Q I:\Windows\inf\prnlx006.inf
DEL /F /Q I:\Windows\inf\prnlx007.inf
DEL /F /Q I:\Windows\inf\prnlx008.inf
DEL /F /Q I:\Windows\inf\prnlx009.inf
DEL /F /Q I:\Windows\inf\prnnr002.inf
DEL /F /Q I:\Windows\inf\prnnr003.inf
DEL /F /Q I:\Windows\inf\prnnr004.inf
DEL /F /Q I:\Windows\inf\prnod002.inf
DEL /F /Q I:\Windows\inf\prnok002.inf
DEL /F /Q I:\Windows\inf\prnok652.inf
DEL /F /Q I:\Windows\inf\prnrc00a.inf
DEL /F /Q I:\Windows\inf\prnrc00b.inf
DEL /F /Q I:\Windows\inf\prnrc00c.inf
DEL /F /Q I:\Windows\inf\prnrc002.inf
DEL /F /Q I:\Windows\inf\prnrc003.inf
DEL /F /Q I:\Windows\inf\prnrc004.inf
DEL /F /Q I:\Windows\inf\prnrc005.inf
DEL /F /Q I:\Windows\inf\prnrc006.inf
DEL /F /Q I:\Windows\inf\prnrc007.inf
DEL /F /Q I:\Windows\inf\prnsa002.inf
DEL /F /Q I:\Windows\inf\prnsh002.inf
DEL /F /Q I:\Windows\inf\prnso002.inf
DEL /F /Q I:\Windows\inf\prnsv002.inf
DEL /F /Q I:\Windows\inf\prnsv003.inf
DEL /F /Q I:\Windows\inf\prnsv004.inf
DEL /F /Q I:\Windows\inf\prnts002.inf
DEL /F /Q I:\Windows\inf\prnts003.inf
DEL /F /Q I:\Windows\inf\prnxx002.inf
DEL /F /Q I:\Windows\inf\ricoh.inf
DEL /F /Q I:\Windows\inf\sti.inf
DEL /F /Q I:\Windows\inf\wave.inf
DEL /F /Q I:\Windows\inf\wiabr00a.inf
DEL /F /Q I:\Windows\inf\wiabr002.inf
DEL /F /Q I:\Windows\inf\wiabr004.inf
DEL /F /Q I:\Windows\inf\wiabr005.inf
DEL /F /Q I:\Windows\inf\wiabr006.inf
DEL /F /Q I:\Windows\inf\wiabr007.inf
DEL /F /Q I:\Windows\inf\wiabr008.inf
DEL /F /Q I:\Windows\inf\wiabr009.inf
DEL /F /Q I:\Windows\inf\wiaca00a.inf
DEL /F /Q I:\Windows\inf\wiaca00b.inf
DEL /F /Q I:\Windows\inf\wiaca00c.inf
DEL /F /Q I:\Windows\inf\wiaca00d.inf
DEL /F /Q I:\Windows\inf\wiaca00e.inf
DEL /F /Q I:\Windows\inf\wiaca00f.inf
DEL /F /Q I:\Windows\inf\wiaca00i.inf
DEL /F /Q I:\Windows\inf\wiacn001.inf
DEL /F /Q I:\Windows\inf\wiaep002.inf
DEL /F /Q I:\Windows\inf\wiaep003.inf
DEL /F /Q I:\Windows\inf\wiahp001.inf
DEL /F /Q I:\Windows\inf\wiaky002.inf
DEL /F /Q I:\Windows\inf\wialx002.inf
DEL /F /Q I:\Windows\inf\wialx003.inf
DEL /F /Q I:\Windows\inf\wialx004.inf
DEL /F /Q I:\Windows\inf\wialx005.inf
DEL /F /Q I:\Windows\inf\wialx006.inf
DEL /F /Q I:\Windows\inf\wiasa002.inf
DEL /F /Q I:\Windows\inf\wiaxx002.inf
DEL /F /Q I:\Windows\inf\xcbdav.inf
pause